#!/bin/sh

echo "Testing compilation"
if ! make compile-test;
then
	echo "ERROR: Code must compile with no errors. Run \`make compile-test\` to see what's wrong."
	exit 1
fi

echo "Testing uncrustify"
if ! make uncrustify-check;
then
	echo "ERROR: Code must comply with uncrustify's config. Run \`make uncrustify-check\` to see what's wrong."
	exit 1
fi

echo "All OK"
exit 0
